settings:
  variables:
    entity_tablet: light.fire_tablet_screen
    entity_browser_mod: media_player.amazon_tablet

    translate_unknown: Nieznany
    translate_idle: Nieaktywny
    translate_home: W domu
    translate_not_home: Poza domem
    translate_available: dostępny
    translate_no_updates: Brak aktualizacji
    translate_update_available: aktualizacja dostępna
    translate_updates_available: aktualizacje dostępne

    translate_on: Wł.
    translate_off: Wył.
    translate_cool: Chłodzenie
    translate_fan_only: Wentylator
    translate_playing: Granie
    translate_paused: Pauza
    translate_standby: Standby