- id: '1730722012692'
  alias: Termostat się przestawił
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - climate.wejscie
    - climate.gabinet
    - climate.salon
    - climate.sypialnia
    - climate.hania
    - climate.wojtek
    - climate.lazienka
    - climate.lazienka_dol
    - climate.piwnica
    - climate.kotlownia
    - climate.wodomierz
    - climate.schowek
    - climate.garaz
    attribute: temperature
    above: 25
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    target:
      entity_id: notify.anarion_iwona_phones
    data:
      message: Czujnik temperatury {{ trigger.entity_id }} się przestawił
      title: Czujnik temperatury się przestawił
  mode: single
- id: '1731958982662'
  alias: Ogłupiały regulator
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - climate.wejscie
    - climate.gabinet
    - climate.salon
    - climate.sypialnia
    - climate.wojtek
    - climate.hania
    - climate.lazienka
    - climate.lazienka_dol
    - climate.piwnica
    - climate.wodomierz
    - climate.kotlownia
    - climate.schowek
    - climate.garaz
    attribute: temperature
    above: 24
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    target:
      entity_id: notify.anarion_iwona_phones
    data:
      message: Regulator ogłupiał!
      title: Regulator ogłupiał!
  mode: single
- id: '1758984849254'
  alias: Powiadomienie o imprezie
  description: ''
  triggers:
  - trigger: time
    at: '18:31:00'
  conditions: []
  actions:
  - action: media_player.volume_set
    data:
      entity_id: media_player.nest_mini
      volume_level: 0.5
  - action: tts.speak
    data:
      media_player_entity_id: media_player.nest_mini
      message: Uwaga! Uwaga! Zbiórka w pokoju Wojtusia! - tam są zapisy.
    target:
      entity_id: tts.google_cloud_2
  mode: single
- id: '1758984936638'
  alias: Powiadomienie o imprezie
  description: ''
  triggers:
  - trigger: time
    at: '18:31:00'
  conditions: []
  actions:
  - action: media_player.volume_set
    data:
      entity_id: media_player.nest_mini
      volume_level: 0.5
  - action: tts.speak
    data:
      media_player_entity_id: media_player.nest_mini
      message: Uwaga uwaga! Zbiórka w pokoju Wojtusia! - tam są zapisy!
    target:
      entity_id: tts.google_cloud_2
  mode: single
- id: '1758985076778'
  alias: Powiadomienie o imprezie
  description: ''
  triggers:
  - trigger: time
    at: '18:31:00'
  conditions: []
  actions:
  - action: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.6
    target:
      device_id: c5223523afacca1b99bf0885aa458b17
  - action: tts.google_cloud_say
    metadata: {}
    data:
      cache: false
      entity_id: media_player.nest_mini
      message: Uwaga Uwaga! Zbiórka w pokoju Wojtusia! - tam są zapisy!
  mode: single
- id: '1778771893492'
  alias: Controller - Aqara WXKG11LM Wireless Mini Switch / Xiaomi WXKG01LM Mi Wireless
    Switch
  description: ''
  use_blueprint:
    path: EPMatt/xiaomi_wxkg11lm.yaml
    input:
      integration: Zigbee2MQTT
      controller_device: f9e03024ccfeee1d059b65296a6d40dd
      action_button_short:
      - action: switch.toggle
        metadata: {}
        target:
          entity_id: switch.tvset
        data: {}
- id: '1778773232526'
  alias: Turn on TV via button
  description: ''
  triggers:
  - domain: mqtt
    device_id: f9e03024ccfeee1d059b65296a6d40dd
    type: action
    subtype: single
    trigger: device
  conditions: []
  actions:
  - action: switch.toggle
    metadata: {}
    target:
      entity_id: switch.tvset
    data: {}
  mode: single
- id: '1778773404250'
  alias: Toggle TVSET
  description: ''
  triggers:
  - domain: mqtt
    device_id: f9e03024ccfeee1d059b65296a6d40dd
    type: action
    subtype: single
    trigger: device
  conditions: []
  actions:
  - action: switch.toggle
    metadata: {}
    target:
      entity_id: switch.tvset
    data: {}
  mode: single
- id: '1785259845802'
  alias: Włącz wentylatory amplitunera gdy TV włączony
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.sony_kd_55xe9305
    from:
    to:
    - 'on'
  - trigger: state
    entity_id:
    - media_player.sony_kd_55xe9305
    from:
    to:
    - 'on'
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: switch.wentylatory_amplitunera_l1
    data: {}
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: switch.wentylatory_amplitunera_l2
    data: {}
  mode: single
- id: '1785259931439'
  alias: Wyłącz wentylatory amplitunera gdy TV wyłączony
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.sony_kd_55xe9305
    from:
    to:
    - 'off'
    - unavailable
  - trigger: state
    entity_id:
    - media_player.sony_kd_55xe9305
    from:
    to:
    - 'off'
    - unavailable
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id: switch.wentylatory_amplitunera_l1
    data: {}
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id: switch.wentylatory_amplitunera_l2
    data: {}
  mode: single
- id: '1789645450983'
  alias: Bateria w tablecie
  description: Bateria w tablecie
  triggers:
  - trigger: state
    entity_id:
    - sensor.tablet2_battery_level
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.kftrwi_battery_level
        above: '80'
      sequence:
      - action: switch.turn_off
        target:
          entity_id: switch.sonoff_1000d4b2e1_1
    - conditions:
      - condition: numeric_state
        entity_id: sensor.kftrwi_battery_level
        below: '20'
      sequence:
      - action: switch.turn_on
        target:
          entity_id: switch.sonoff_1000d4b2e1_1
    default: []
  mode: restart
- id: '1789645568016'
  alias: homeassistant_start
  description: ''
  triggers:
  - trigger: homeassistant
    event: start
  conditions: []
  actions:
  - action: button.press
    data: {}
    target:
      entity_id: button.salon_samsung_tablet_uruchom_ponownie_przegladarke
  mode: single
- id: '1789645584151'
  alias: fullykiosk_close_popups_disable_screen
  description: Close popups when screensaver is enabled
  triggers:
  - trigger: state
    entity_id:
    - switch.salon_samsung_tablet_wygaszacz_ekranu
    to:
    - 'on'
  conditions: []
  actions:
  - action: browser_mod.close_popup
  mode: restart
- id: '1789645595571'
  alias: fullykiosk_enable_screen_brightness
  description: Set brightness when screen enabled
  triggers:
  - trigger: state
    entity_id:
    - switch.salon_samsung_tablet_wygaszacz_ekranu
    from:
    - 'on'
    to:
    - 'off'
  conditions: []
  actions:
  - action: number.set_value
    target:
      entity_id: number.salon_samsung_tablet_jasnosc_wygaszacza_ekranu
    data:
      value: '{% set day_percent = 90 %} {% set night_percent = 65 %} {% set day_convert
        = ((day_percent * 255) / 100) | int %} {% set night_convert = ((night_percent
        * 255) / 100) | int %} {{ iif(is_state(''sun.sun'', ''above_horizon''), day_convert,
        night_convert) }}

        '
  mode: restart
