homeassistant:
  name: Hem
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Stockholm
  packages: !include_dir_named include
  allowlist_external_dirs: [/config/]

default_config:

lovelace:
  mode: yaml
  resources:
    [ { url: /hacsfiles/bar-card/bar-card.js,                               type: module },
      { url: /hacsfiles/button-card/button-card.js,                         type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js,                           type: module },
      { url: /hacsfiles/light-entity-card/light-entity-card.js,             type: module },
      { url: /hacsfiles/light-popup-card/light-popup-card.js,               type: module },
      { url: /hacsfiles/lovelace-card-mod/card-mod.js,                      type: module },
      { url: /hacsfiles/lovelace-hui-element/hui-element.js,                type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,    type: module },
      { url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js,    type: module },
      { url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,          type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                           type: module },
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                 type: module },
      { url: /hacsfiles/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js,   type: module },
      { url: /hacsfiles/purifier-card/purifier-card.js,   type: module },
      { url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js,   type: module },
      { url: /hacsfiles/config-template-card/config-template-card.js,   type: module },
      { url: /hacsfiles/lovelace-weather-card-chart/weather-card-chart.js,   type: module },
      { url: /hacsfiles/lovelace-auto-entities/auto-entities.js,   type: module },
      { url: /hacsfiles/air-visual-card/air-visual-card.js,   type: module },
      
      { url: /hacsfiles/ha-card-weather-conditions/ha-card-weather-conditions.js,   type: module },
      { url: /hacsfiles/ha-floorplan/floorplan.js,   type: module },
      { url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js,   type: module },
      { url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,   type: module },
      { url: /hacsfiles/zha-network-card/zha-network-card.js,   type: module },
      
      { url: /hacsfiles/generic-remote-control-card/generic-remote-control-card.js,   type: module },
      { url: /hacsfiles/entity-attributes-card/entity-attributes-card.js,   type: module },
      { url: /hacsfiles/search-card/search-card.js,   type: module },
      { url: /hacsfiles/garbage-collection-card/garbage-collection-card.js,   type: module },
      { url: /hacsfiles/lovelace-swipe-navigation/lovelace-swipe-navigation.js,   type: module },
      
      { url: /hacsfiles/tv-card/tv-card.js,   type: module },
      { url: /hacsfiles/tv-card/tv-card-editor.js,   type: module },
      { url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js,   type: module },
      { url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js,   type: module },
      { url: /hacsfiles/uptime-card/uptime-card.js,   type: module },
      { url: /hacsfiles/lovelace-battery-entity-row/battery-entity-row.js,   type: module },
      
      { url: /hacsfiles/lovelace-state-switch/state-switch.js,   type: module },
      { url: /hacsfiles/lovelace-gui-sandbox/gui-sandbox.js,   type: module },
      { url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js,   type: module },
      { url: /hacsfiles/lovelace-weather-card-chart/weather-card-chart.js,   type: module },
      { url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js,   type: module },
      { url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js,   type: module },
      { url: /hacsfiles/power-wheel-card/power-wheel-card.js,   type: module },
      { url: /hacsfiles/popup-backdrop-filter/popup-backdrop-filter.js,   type: module },

      { url: '/local/calendar-card.js?v=31091',                             type: module },
      { url: '/local/custom_icons.js?v=25052001',                           type: module },
      { url: '/local/font.css',                                               type: css    } ] 

logger:
  default: warning
  logs:
    homeassistant.components.websocket_api: fatal
    homeassistant.components.bluetooth_tracker.device_tracker: fatal

recorder:
  db_url: !secret recorder_db_url

person:
  - name: Matte
    id: matte
    device_trackers:
      - device_tracker.mattias_iphone_ios
      - device_tracker.mattias_iphonedetect
      - device_tracker.mattias_iphone_unifi
      - device_tracker.mattias_bluetooth

  - name: Sanja
    id: sanja
    device_trackers:
      - device_tracker.sanja_iphonedetect
      - device_tracker.sanjas_iphone_unifi
      - device_tracker.sanja_bluetooth

device_tracker:
  - platform: bluetooth_tracker
    new_device_defaults:
      track_new_devices: false

  - platform: iphonedetect
    consider_home: 60
    scan_interval: 12
    new_device_defaults:
      track_new_devices: false
    hosts:
      mattias_iphonedetect: !secret iphonedetect_matte
      sanja_iphonedetect: !secret iphonedetect_sanja

wemo:
  discovery: false
  static: !secret wemo_static

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

browser_mod:
  devices:
    c2080cea-6627150a:
      name: galaxy_tab_a
  disable:
    - all

timer:
  laundry:
    duration: 01:00:00
    icon: mdi:washing-machine

lock:
  - platform: template
    name: Dator
    value_template: "{{ states('input_boolean.computer_lock') }}"
    lock:
      service: input_boolean.turn_on
      entity_id: input_boolean.computer_lock
    unlock:
      service: input_boolean.turn_off
      entity_id: input_boolean.computer_lock

ios:
  push:
    categories:
      - name: Home Assistant
        identifier: ios_hass
        actions:
          - identifier: start_watchtower
            title: Uppdatera
