
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
mobile_app:
discovery:
conversation:
api:
websocket_api:
stream:
media_source:
lovelace:
  mode: storage
  resources:
    [ { url: /hacsfiles/bar-card/bar-card.js,                               type: module },
      { url: /hacsfiles/button-card/button-card.js,                         type: module },
      { url: /local/kiosk-mode.js?v=1.7.2,                                  type: module },
      { url: /hacsfiles/browser_mod/browser_mod.js,                         type: module },
      { url: /hacsfiles/light-entity-card/light-entity-card.js,             type: module },
      { url: /hacsfiles/light-popup-card/light-popup-card.js,               type: module },
      #{ url: /hacsfiles/lovelace-card-mod/card-mod.js,                      type: module },
      { url: /hacsfiles/lovelace-hui-element/hui-element.js,                type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,    type: module },
      { url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js,    type: module },
      { url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,          type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                           type: module },
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                 type: module },
      { url: /hacsfiles/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js,   type: module },
      { url: /hacsfiles/purifier-card/purifier-card.js,                     type: module },
      { url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js, type: module },
      { url: /hacsfiles/config-template-card/config-template-card.js,       type: module },
      { url: /hacsfiles/lovelace-weather-card-chart/weather-card-chart.js,  type: module },
      { url: /hacsfiles/lovelace-auto-entities/auto-entities.js,            type: module },
      { url: /hacsfiles/air-visual-card/air-visual-card.js,                 type: module },
      #{ url: /hacsfiles/alarmo-card/alarmo-card.js,                 type: module },
      #{ url: '/local/hold_action_fix.js?v=1',                               type: module },

      { url: /hacsfiles/ha-card-weather-conditions/ha-card-weather-conditions.js,   type: module },
      { url: /hacsfiles/ha-floorplan/floorplan.js,                                  type: module },
      { url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js,                  type: module },
      { url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,              type: module },
      { url: /hacsfiles/zha-network-card/zha-network-card.js,                       type: module },
      { url: /hacsfiles/home-feed-card/lovelace-home-feed-card.js,                  type: module },
      { url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js,           type: module },

      { url: /hacsfiles/generic-remote-control-card/generic-remote-control-card.js, type: module },
      { url: /hacsfiles/entity-attributes-card/entity-attributes-card.js,           type: module },
      { url: /hacsfiles/search-card/search-card.js,                                 type: module },
      { url: /hacsfiles/garbage-collection-card/garbage-collection-card.js,         type: module },
      {  url: /local/swipe-navigation.js?v=1.3.6,                                   type: module },

      { url: /hacsfiles/tv-card/tv-card.js,                                   type: module },
      { url: /hacsfiles/tv-card/tv-card-editor.js,                            type: module },
      { url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js,  type: module },
      { url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js,    type: module },
      { url: /hacsfiles/uptime-card/uptime-card.js,                           type: module },
      { url: /hacsfiles/lovelace-battery-entity-row/battery-entity-row.js,    type: module },
      { url: /hacsfiles/lovelace-more-info-card/more-info-card.js,            type: module },

      { url: /hacsfiles/lovelace-state-switch/state-switch.js,               type: module },
      { url: /hacsfiles/lovelace-gui-sandbox/gui-sandbox.js,                 type: module },
      { url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js, type: module },
      { url: /hacsfiles/lovelace-weather-chart-card/weather-chart-card.js,   type: module },
      { url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js,         type: module },
      { url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js,       type: module },
      { url: /hacsfiles/power-wheel-card/power-wheel-card.js,                type: module },
      { url: /hacsfiles/popup-backdrop-filter/popup-backdrop-filter.js,      type: module },
      { url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js,    type: module },

      { url: '/local/calendar-card.js',                                     type: module },
      { url: '/local/custom_icons.js',                                      type: module },
      { url: '/local/marked.min.js?v=4.0.12',                               type: module },
      { url: '/local/vanilla-tilt.min.js?v=1.7.2',                          type: module },
      { url: '/local/font.css',                                             type: css    } ]

  dashboards:
    lovelace-tablet:
      mode: yaml
      title: Tablet
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      filename: ui-lovelace-tablet.yaml

homeassistant:
  packages: !include_dir_named include
  allowlist_external_dirs:
    - /config
    - /config/www








