action: fire-dom-event
browser_mod:
  command: popup
  title: Ustawienia
  style:
    .: |
      :host .content {
        width: 600px;
        max-width: 90vw;
      }
      /* phone */
      @media screen and (max-width: 800px) {
        :host .content {
          max-width: 100vw;
        }
      }
    hui-vertical-stack-card:
      $: |
        hui-horizontal-stack-card {
          padding: 0em 2em 2.3em 2em;
        }
      $hui-horizontal-stack-card$: |
        #root {
          justify-content: space-evenly;
        }
  card:
    type: vertical-stack
    cards:
      - type: entities
        state_color: true
        card_mod:
          class: content
        entities:

          - type: custom:slider-entity-row
            entity: input_number.watering_time

          - type: custom:hui-horizontal-stack-card
            cards:
              - type: custom:button-card
                name: Uruchom zraszacz
                icon: mdi:sprinkler-variant
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.sprinkler
                    variables:
                      minutes: >
                        [[[ return states['input_number.watering_time'].state; ]]]
                template: icon_name