binary_sensor:

    ####################################################
    #                                                  #
    #                  BINARY SENSOR                   #
    #                                                  #
    ####################################################

  - platform: command_line
    name: plex_availability
    command: !secret plex_availability
    scan_interval: 300

  - platform: ping
    name: nas_internet_access
    host: 8.8.8.8