binary_sensor:

    ####################################################
    #                                                  #
    #                  BINARY SENSOR                   #
    #                                                  #
    ####################################################

  - platform: command_line
    name: plex_availability
    command: !secret plex_availability
    scan_interval: 300

  - platform: ping
    name: nas_internet_access
    host: 8.8.8.8

  - platform: burze_dzis_net
    api_key: !secret burze_dzis_net.api_key
    name: Storm warning
    latitude: !secret burze_net_latitude
    longitude: !secret burze_net_longitude
    warnings:
      - frost_warning
      - heat_warning
      - wind_warning
      - precipitation_warning
      - storm_warning
      - tornado_warning
    storms_nearby:
      radius: 30

  - platform: template
    sensors:
      ac:
        friendly_name: AC
        value_template: >
            {{ 'on' if states('climate.living_room_ac') in ['heat_cool', 'cool', 'heat', 'dry', 'fan_only'] else 'off' }}
      komfovent_status_starting:
        friendly_name: "Komfovent Status - Starting"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(1) > 0 }}"
      komfovent_status_stopping:
        friendly_name: "Komfovent Status - Stopping"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(2) > 0 }}"
      komfovent_status_fan:
        friendly_name: "Komfovent Status - Fan"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(4) > 0 }}"
      komfovent_status_rotor:
        friendly_name: "Komfovent Status - Rotor"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(8) > 0 }}"
      komfovent_status_heating:
        friendly_name: "Komfovent Status - Heating"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(16) > 0 }}"
      komfovent_status_cooling:
        friendly_name: "Komfovent Status - Cooling"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(32) > 0 }}"
      komfovent_status_heatingdenied:
        friendly_name: "Komfovent Status - Heating Denied"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(64) > 0 }}"
      komfovent_status_coolingdenied:
        friendly_name: "Komfovent Status - Cooling Denied"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(128) > 0 }}"
      komfovent_status_flow_down:
        friendly_name: "Komfovent Status - Flow Down"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(256) > 0 }}"
      komfovent_status_free_heating:
        friendly_name: "Komfovent Status - Free Heating"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(512) > 0 }}"
      komfovent_status_free_cooling:
        friendly_name: "Komfovent Status - Free Cooling"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(1024) > 0 }}"
      komfovent_status_alarm_f:
        friendly_name: "Komfovent Status - Alarm F"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(2048) > 0 }}"
      komfovent_status_alarm_w:
        friendly_name: "Komfovent Status - Alarm W"
        value_template: "{{ states('sensor.Komfovent_status')|int(0)|bitwise_and(4096) > 0 }}"
      komfovent_mode_is_away:
        friendly_name: "Komfovent mode is Away"
        value_template: "{{ states('sensor.komfovent_mode_num') | int(default=0) == 1 }}"
      komfovent_mode_is_normal:
        friendly_name: "Komfovent mode is Normal"
        value_template: "{{ states('sensor.komfovent_mode_num') | int(default=0) == 2 }}"
      komfovent_mode_is_intensive:
        friendly_name: "Komfovent mode is Intensive"
        value_template: "{{ states('sensor.komfovent_mode_num') | int(default=0) == 3 }}"
      komfovent_mode_is_boost:
        friendly_name: "Komfovent mode is Boost"
        value_template: "{{ states('sensor.komfovent_mode_num') | int(default=0) == 4 }}"

  - platform: antistorm
    station_id: 148
    monitored_conditions:
      - 'storm_alarm'
      - 'rain_alarm'
      - 'storm_active'

  - name: "Anarion Home"
    platform: "bayesian"
    prior: 0.9
    probability_threshold: 0.7
    observations:
      - platform: template
        value_template: >
          {{is_state('device_tracker.nokia_8_3_5g','not_home') and ((as_timestamp(now()) - as_timestamp(states.device_tracker.nokia_8_3_5g.last_changed)) > 300)}}
        prob_given_true: 0.8
      - platform: template
        value_template: >
          {{is_state('device_tracker.a2_2b_19_c3_2b_cd','not_home') and ((as_timestamp(now()) - as_timestamp(states.device_tracker.a2_2b_19_c3_2b_cd.last_changed)) > 300)}}
        prob_given_true: 0.95

  - platform: meteoalarm
    country: "Poland"
    province: "malopolska"
    language: "pl-PL"