binary_sensor:

    ####################################################
    #                                                  #
    #                  BINARY SENSOR                   #
    #                                                  #
    ####################################################

  - platform: command_line
    name: plex_availability
    command: !secret plex_availability
    scan_interval: 300

  - platform: ping
    name: nas_internet_access
    host: 8.8.8.8

  - platform: template
    sensors:
      laundry_time_trigger:
        value_template: >
          {% set start_time = state_attr('calendar.tvatta', 'start_time') %}
          {{ as_timestamp(start_time) - as_timestamp(now()) < 10 * 60 if start_time != None }}

      sidebar_update_color:
        value_template: >
          {% set installed = states('sensor.hass_version_installed') %}
          {% set latest = states('sensor.hass_version_latest') 
            if not installed | regex_search('b') else states('sensor.hass_version_latest_beta') %}
          {% if (installed != latest and installed != 'unknown' and latest != 'unknown') 
            or (states('sensor.hacs') | int > 0 and states('sensor.hacs') != 'unknown') %}
            True
          {% else %}
            False
          {% endif %}
