template:

  ####################################################
  #                                                  #
  #                     TEMPLATE                     #
  #                                                  #
  ####################################################

  sensor:
    - unique_id: sidebar
      state: template
      attributes:
        time: >
          {% set hours = now().strftime('%H') %}
          {% set minutes = now().strftime('%M') %}
          <span class="time">
            {{ hours }}<span class="time-colon">:</span>{{ minutes }}
          </span>
        date: |
          <font color='#6a7377'><b>
          {%- if strptime(states('sensor.date'), '%Y-%m-%d').day != null %}
          {%- set days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
          {%- set months = ['January', 'February', 'March', 'April', 'May', 'June',
          'July', 'August', 'September', 'October', 'November', 'December'] %}
            {{- days[now().weekday()] }}<br>
            {{- strptime(states('sensor.date'), '%Y-%m-%d').day }} {{ months[now().month-1] }}
          {%- endif -%}
          </b></font>
        greet: |
          <b>
          {%- set time = now().hour %}
          {%- if time <= 1 -%} Good night {{'\U0001F611'}}
          {%- elif time <= 3 -%} Good night{{'\U0001F62A'}}
          {%- elif time <= 5 -%} Good night {{'\U0001F634'}}
          {%- elif time <= 7 -%} Good morning {{'\U0001F4A9'}}
          {%- elif time <= 9 -%} Good morning {{'\u2615\uFE0F'}}
          {%- elif time <= 10 -%} Good morning {{'\U0001F642'}}
          {%- elif time <= 13 -%} Good day {{'\U0001F60A'}}
          {%- elif time <= 15 -%} Good day {{'\U0001F60E'}}
          {%- elif time <= 17 -%} Good day {{'\U0001F44B\U0001F3FB'}}
          {%- elif time <= 19 -%} Good evening {{'\U0001F44B\U0001F3FB'}}
          {%- elif time <= 22 -%} Good evening {{'\U0001F60C'}}
          {%- elif time <= 23 -%} Good evening {{'\U0001F974'}}
          {%- else %} Good evening {{'\U0001F974'}}
          {%- endif -%}
          </b>
        active: |
          <b>
          {%- set lights = [
            states.light.tv,
            states.light.yeelight_hania,
            states.light.horna,
            states.light.dator,
            states.light.vask_hoger,
            states.light.vask_vanster,
            states.light.byra,
            states.light.garderob,
            states.light.hall_1,
            states.light.hall_2,
            states.light.hall_3,
            states.light.mattias,
            states.light.sanja,
            states.light.spot_1,
            states.light.spot_2,
            states.switch.balkong
          ] %}

          {%- set switches = [
            states.switch.router,
            states.switch.tv,
            states.switch.smart_plug_2,
            states.switch.playstation_5,
            states.switch.wemo_monitors,
            states.binary_sensor.ac,
            states.fan.zhimi_airpurifier_v7
          ] %}

          {%- set lights_on = lights | selectattr('state','eq','on') | list %}
          {%- set lights_name = lights | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}

          {%- set switches_on = switches | selectattr('state','eq','on') | list %}
          {%- set switches_name = switches | selectattr('state','eq','on') | map(attribute='name') | join(', ') %}

          {%- if (lights_on | length == 0) and (switches_on | length == 1) -%}
            {{ switches_name | regex_replace(',([^,]*)$',' and\\1') }} is on

          {%- elif (lights_on | length == 0) and (switches_on | length > 1) -%}
            {{ switches_name | regex_replace(',([^,]*)$',' and\\1') }} are on

          {%- elif (lights_on | length == 1) and (switches_on | length == 1) -%}
            {{ lights_name }} and {{switches_name }} are on

          {%- elif (lights_on | length == 1) and (switches_on | length > 1) -%}
            {{ lights_name }}, {{ switches_name | regex_replace(',([^,]*)$',' and\\1') }} are on

          {%- elif (lights_on | length > 1) and (switches_on | length == 1) -%}
            {{ lights_on | length }} lights and {{ switches_name }} are on

          {%- elif (lights_on | length > 1) and (switches_on | length > 1) -%}
            {{ lights_on | length }} lights, {{ switches_name | regex_replace(',([^,]*)$',' and\\1') }} are on

          {%- elif (lights_on | length == 1) and (switches_on | length == 0) -%}
            {{ lights_name }} is on

          {%- elif (lights_on | length > 1) and (switches_on | length == 0) -%}
            {{ lights_on | length }} lights are on

          {%- else %}
            <font color='#6a7377'>Everything is off</font>
          {%- endif -%}
          </b>
        vacuum: |
          {% set entity_id = 'vacuum.valetudo_robot' %}
          {%- if is_state(entity_id, 'cleaning') -%}
            <b>Morty is cleaning</b>
          {%- elif is_state(entity_id, 'returning') -%}
            <b>Morty is done</b>
          {%- endif %}
        weather: |
          {%- set temperature = states('sensor.openweathermap_temperature') %}
          {%- set condition = states('sensor.openweathermap_condition') %}
          {%- set weather_icon = '' %}
          {%- if condition == 'clear-night' -%} {{ weather_icon }} {{'\U0001F315'}}
          {%- elif condition == 'cloudy' -%} {{ weather_icon }} {{'\U00002601\U0000FE0F'}}
          {%- elif condition == 'exceptional' -%} {{ weather_icon }} {{'\U0001F31E'}}
          {%- elif condition == 'fog' -%} {{ weather_icon }} {{'\U0001F32B\U0000FE0F'}}
          {%- elif condition == 'hail' -%} {{ weather_icon }} {{'\U000026AA'}}
          {%- elif condition == 'lightning' -%} {{ weather_icon }} {{'\U0001F329\U0000FE0F'}}
          {%- elif condition == 'lightning-rainy' -%} {{ weather_icon }} {{'\U000026C8\U0000FE0F'}}
          {%- elif condition == 'partlycloudy' -%} {{ weather_icon }} {{'\U0001F324\U0000FE0F'}}
          {%- elif condition == 'pouring' -%} {{ weather_icon }} {{'\U00002614'}}
          {%- elif condition == 'rainy' -%} {{ weather_icon }} {{'\U00002602\U0000FE0F'}}
          {%- elif condition == 'snowy' -%} {{ weather_icon }} {{'\U00002744\U0000FE0F'}}
          {%- elif condition == 'snowy-rainy' -%} {{ weather_icon }} {{'\U0001F328\U0000FE0F'}}
          {%- elif condition == 'sunny' -%} {{ weather_icon }} {{'\U00002600\U0000FE0F'}}
          {%- elif condition == 'windy' -%} {{ weather_icon }} {{'\U0001F32C\U0000FE0F'}}
          {%- elif condition == 'windy-variant' -%} {{ weather_icon }} {{'\U0001F390'}}
          {%- endif -%}
          {%- set apparent = states('sensor.openweathermap_feels_like_temperature') | round %}
          {%- set precip = states('sensor.openweathermap_forecast_precipitation_probability') | round %}
          {% if not is_state('sensor.openweathermap_temperature', 'unknown') %}
            {%- if temperature | float <= 0.0 -%}
              {{ weather_icon }} Feels like {{ apparent }}° with {{ precip }}% risk of snow {{'\u2744\uFE0F'}}
            {%- elif temperature | float > 0.0 -%}
              {{ weather_icon }} Feels like {{ apparent}}° with {{ precip }}% risk of rain {{ '\u2614\uFE0F' if precip > 30 }}
            {%- endif %}
          {%- else %}
            Unable to load weather information...
          {%- endif %}
 #       transport: |
 #         {% set entity_id = 'sensor.stopa_bazowa_pko_bp' %}
 #           Stopa bazowa NBP wynosi {{ states('sensor.stopa_bazowa_pko_bp') }}
        laundry: |
          {%- set start_time = state_attr('calendar.tvatta', 'start_time') %}
          {% if start_time != None %}
            {%- set time = as_timestamp(start_time) | timestamp_custom('%H:%M') %}
            {%- set hours = as_timestamp(start_time) | timestamp_custom('%H') | int / 24 %}
            {%- set count = (as_timestamp(start_time) - as_timestamp(now())) / 86400 - hours %}
            {%- set day = strptime(start_time, '%Y-%m-%d %H:%M:%S').strftime('%A')
            | replace('Monday', 'Monday')
            | replace('Tuesday', 'Tuesday')
            | replace('Wednesday', 'Wednesday')
            | replace('Thursday', 'Thursday')
            | replace('Friday', 'Friday')
            | replace('Saturday', 'Saturday')
            | replace('Sunday', 'Sunday') %}
            {%- if count <= 0.0 -%}
              {{'\U0001F4A6'}} Wash today {{ time }}
            {%- elif count <= 1.0 -%}
              Wash tomorrow at  {{ time }}
            {%- elif count <= 2.0 -%}
              Wash the day after tomorrow at  {{ time }}
            {%- else -%}
              Wash again {{ (count + hours) | round }} days on {{ day }} at {{ time }}
            {%- endif %}
          {%- endif %}
        battery: |
          {% set entities = [
            'sensor.button1_battery',
            'sensor.door_sensor_1_battery',
            'sensor.switch1_battery',
            'sensor.ipad_iwona_battery_level',
            'sensor.motion_sensor_1_battery',
            'sensor.nokia_8_3_5g_battery_level',
            'sensor.ta_1004_poziom_baterii',
            'sensor.fire_tablet_battery_level',
            'sensor.redmi_note_5_battery_level' ] %}
          {%- for sensor in entities if states(sensor) | int <= 20 and states(sensor) != 'unknown' %}
            {%- if loop.first %} {{-'\u26A0\uFE0F'}} Battery: {% else %}, {% endif -%}
            {{ state_attr(sensor, 'friendly_name') + ' ' +  states(sensor) + '%' }}
          {%- endfor %}
        calendar: |
          {%- set start_time = state_attr('calendar.anarion_dunedain', 'start_time') %}
          {%- set end_time = state_attr('calendar.anarion_dunedain', 'end_time') %}
          {%- set event = state_attr('calendar.anarion_dunedain', 'message') %}
          {%- set location = state_attr('calendar.anarion_dunedain', 'location') %}
          {% if start_time != None %}
            {%- set time = as_timestamp(start_time) | timestamp_custom('%H:%M') %}
            {%- set time_end = as_timestamp(end_time) | timestamp_custom('%H:%M') %}
            {%- set hours = as_timestamp(start_time) | timestamp_custom('%H') | int / 24 %}
            {%- set count = (as_timestamp(start_time) - as_timestamp(now())) / 86400 - hours %}
            {%- set day = strptime(start_time, '%Y-%m-%d %H:%M:%S').strftime('%A') 
            | replace('Monday', 'Monday')
            | replace('Tuesday', 'Tuesday')
            | replace('Wednesday', 'Wednesday')
            | replace('Thursday', 'Thursday')
            | replace('Friday', 'Friday')
            | replace('Saturday', 'Saturday')
            | replace('Sunday', 'Sunday') %}
            {%- if count <= 0.0 -%}
              {{'\U0001F4C5'}} {{ event }} today between {{ time }}-{{ time_end }}
            {%- elif count <= 1.0 -%}
              {{ event}} tomorrow between {{ time }}-{{ time_end }}
            {%- elif count <= 2.0 -%}
              {{ event}} the day after tomorrow between {{ time }}-{{ time_end }}
            {%- else -%}
              {{event }} in {{ (count + hours) | round }} days on {{ day }} between {{ time }}-{{ time_end }}
            {%- endif %}
          {%- endif %}

        plex: |
          {% if is_state('binary_sensor.plex_availability', 'off') -%}
            {{-'\u26A0\uFE0F'}} Plex is down...
          {%- endif %}
        # nas: |
          # {% if is_state('binary_sensor.nas_internet_access', 'off') -%}
            # {{-'\u26A0\uFE0F'}} Check NAS Internet access
          # {%- endif %}

    - unique_id: sidebar_calendar
      state: template
      attributes:
        calendar: |
          {%- set start_time = state_attr('calendar.anarion_dunedain', 'start_time') %}
          {%- set end_time = state_attr('calendar.anarion_dunedain', 'end_time') %}
          {%- set event = state_attr('calendar.anarion_dunedain', 'message') %}
          {%- set location = state_attr('calendar.anarion_dunedain', 'location') %}
          {% if start_time != None %}
            {%- set time = as_timestamp(start_time) | timestamp_custom('%H:%M') %}
            {%- set time_end = as_timestamp(end_time) | timestamp_custom('%H:%M') %}
            {%- set hours = as_timestamp(start_time) | timestamp_custom('%H') | int / 24 %}
            {%- set count = (as_timestamp(start_time) - as_timestamp(now())) / 86400 - hours %}
            {%- set day = strptime(start_time, '%Y-%m-%d %H:%M:%S').strftime('%A')
            | replace('Monday', 'Monday')
            | replace('Tuesday', 'Tuesday')
            | replace('Wednesday', 'Wednesday')
            | replace('Thursday', 'Thursday')
            | replace('Friday', 'Friday')
            | replace('Saturday', 'Saturday')
            | replace('Sunday', 'Sunday') %}
            {%- if count <= 0.0 -%}
              {{'\U0001F4C5'}} {{ event }} today between {{ time }}-{{ time_end }}
            {%- elif count <= 1.0 -%}
              {{ event}} tomorrow between {{ time }}-{{ time_end }}
            {%- elif count <= 2.0 -%}
              {{ event}} the day after tomorrow between {{ time }}-{{ time_end }}
            {%- else -%}
              {{event }} {{ (count + hours) | round }} days on {{ day }} between {{ time }}-{{ time_end }}
            {%- endif %}
          {%- endif %}

    - unique_id: coronavirus
      icon: mdi:virus
      state: template
      attributes:
        template: >
            {% set break = '‍ ‍ ‍ ‍ ‍ ‍<font color="#2f3436">|</font> ‍ ‍ ‍ ‍ ' %}
            <font color='#6a7377'>
            <ha-icon icon="mdi:virus"></ha-icon> <b>Coronavirus</b>{{ break -}}
            <ha-icon icon="mdi:emoticon-sad"></ha-icon> <b>{{ states('sensor.covid19_infections') }}</b> cases{{ break -}}
            <ha-icon icon="mdi:grave-stone"></ha-icon> <b>{{ states('sensor.covid19_deaths') }}</b> deceased{{ break -}}
            <ha-icon icon="mdi:emoticon-happy"></ha-icon> <b>{{ states('sensor.covid19_recovered') }}</b> recovered
            </font>

    # - unique_id: public_ip
      # icon: mdi:ip
      # state: !secret public_ip

    # - unique_id: dockermon_mem
      # icon: mdi:memory
      # state: >
        # {% set entity_id = 'sensor.docker_cpu' %}
        # {{ (state_attr(entity_id, 'memory_stats')['usage'] /
        # state_attr(entity_id, 'memory_stats')['limit'] * 100) | round(1) | default(0) }}

    - unique_id: imac_vpn
      state: >
        {{ 'Not connected' if is_state('switch.computer_imac', 'on') and
        states('sensor.imac_ip') == states('sensor.template_public_ip') else 'Connected' }}
      icon: >
        mdi:shield-{{ 'alert' if is_state('switch.computer_imac', 'on') and
        states('sensor.imac_ip') == states('sensor.template_public_ip') else 'check' }}

    - unique_id: printer_status
      icon: mdi:printer-wireless
      state: >
        {% macro prt(state, translate) %}
        {{ translate if states('sensor.hp_deskjet_2600_series') == state }}
        {% endmacro %}
        {{ prt('On', 'On') }}
        {{ prt('Scanning', 'Scanning') }}
        {{ prt('Copying', 'Copying') }}
        {{ prt('Printing', 'Printing') }}
        {{ prt('Cancelling Job', 'Cancelling Job') }}
        {{ prt('trayEmptyOrOpen', 'trayEmptyOrOpen') }}
        {{ prt('idle', 'idle') }}
        {{ prt('Off', 'Off') }}

    # - unique_id: vacuum_filter
      # icon: custom:roborock-filter
      # unit_of_measurement: '%'
      # state: >
        # {{ (state_attr('vacuum.morty', 'filter_left') / 1.5) | round }}

    # - unique_id: vacuum_mainbrush
      # icon: custom:roborock-mainbrush
      # unit_of_measurement: '%'
      # state: >
        # {{ (state_attr('vacuum.morty', 'main_brush_left') / 3) | round }}

    # - unique_id: vacuum_sensors
      # icon: custom:roborock-sensor
      # unit_of_measurement: '%'
      # state: >
        # {{ (state_attr('vacuum.morty', 'sensor_dirty_left') / 0.3) | round }}

    # - unique_id: vacuum_sidebrush
      # icon: custom:roborock-sidebrush
      # unit_of_measurement: '%'
      # state: >
        # {{ (state_attr('vacuum.morty', 'side_brush_left') / 2) | round }}

    # - unique_id: vacuum_lastclean
      # icon: mdi:calendar-clock
      # device_class: timestamp
      # state: >
        # {{ state_attr('vacuum.morty', 'clean_stop') | replace(' ','T') }}

    - unique_id: fullykiosk_storage
      icon: mdi:sd
      unit_of_measurement: '%'
      state: >
        {% set FreeSpace = states('sensor.fire_tablet_internal_storage_free_space') | float %}
        {% set TotalSpace = states('sensor.fire_tablet_internal_storage_total_space') | float %}
        {% if not (FreeSpace == 0.0 or TotalSpace == 0.0) %}
          {{ 100 - (FreeSpace / TotalSpace * 100) | int }}
        {% endif %}

    - unique_id: fullykiosk_memory
      icon: mdi:memory
      unit_of_measurement: '%'
      state: >
        {% set FreeMemory = states('sensor.fire_tablet_ram_free_memory') | float %}
        {% set TotalMemory = states('sensor.fire_tablet_ram_total_memory') | float %}
        {% if not (FreeMemory == 0.0 or TotalMemory == 0.0) %}
          {{ 100 - (FreeMemory / TotalMemory * 100) | int }}
        {% endif %}

    - unique_id: fullykiosk_last_app_start
      icon: mdi:update
      device_class: timestamp
      state: >
        {{ states('sensor.fire_tablet_last_app_start') }}

    - unique_id: nas_status
      icon: custom:synology-nas
      state: >
        {% set entity_id = 'sensor.nas_volume_1_status' %}
        {% if is_state(entity_id, 'normal') %}
          Good
        {% elif is_state(entity_id, 'background') %}
          Verifier
        {% else %}
          {{ states(entity_id) }}
        {% endif %}

    - unique_id: nas_vpn
      state: >
        {{ 'Not connected' if states('sensor.myip') == states('sensor.template_public_ip') else 'Connected' }}
      icon: >
        mdi:shield-{{ 'alert' if states('sensor.myip') == states('sensor.template_public_ip') else 'check' }}

#legacy
sensor:

  - platform: template
    sensors:
      hass_version:
        icon_template: mdi:home-assistant
        friendly_name_template: >
          Installed {{ states('sensor.hass_version_installed') }}
        value_template: >
          {{ 'Latest' if states('sensor.hass_version_installed') ==
          states('sensor.hass_version_latest') else states('sensor.hass_version_latest') }}

      hass_dev_release:
        icon_template: mdi:dev-to
        device_class: timestamp
        friendly_name_template: >
          {% set release = state_attr('calendar.home_assistant_devs','message') %}
          {% if release == 'Home Assistant Core Beta Release' %}
            Next beta
          {% elif release == 'Home Assistant Core Release' %}
            Next release
          {% else %}
            {{ release }}
          {% endif %}
        value_template: >
          {{ state_attr('calendar.home_assistant_devs', 'start_time') | replace(' ','T') }}

      nas_net_down:
        value_template: ' '
        icon_template: mdi:arrow-down-bold
        friendly_name_template: >
          {% set down = states('sensor.nas_network_down') | float(default=0) %}
          {% if down < 1000 %} {{ down | round(0) }} kb/s
          {% elif down >= 1000 %} {{ ((down / 1000) | round(2) | string).rstrip('.0') }} Mb/s
          {% endif %}

      nas_net_up:
        value_template: ' '
        icon_template: mdi:arrow-up-bold
        friendly_name_template: >
          {% set up = states('sensor.nas_network_up') | float(default=0) %}
          {% if up < 1000 %} {{ up | round(0) }} kb/s
          {% elif up >= 1000 %} {{ ((up / 1000) | round(2) | string).rstrip('.0') }} Mb/s
          {% endif %}
