automation:
  - id: "1635431265506"
    alias: Dryer finished
    description: ""
    trigger:
      - entity_id: binary_sensor.suszarka_run_completed
        trigger: state
        to: "on"
    condition: []
    action:
      - action: notify.send_message
        target:
          entity_id: notify.anarion_iwona_phones
        data:
          message: >
            {{ '🏁 ' + ['Pranie wysuszone', 'Czas wyjąć pranie', 'Suszenie się skończyło'] | random }}
      - action: media_player.volume_set
        data:
          entity_id: media_player.nest_mini
          volume_level: 0.4
      - action: tts.speak
        data:
          media_player_entity_id: media_player.nest_mini
          message: >
            {{ ['Pranie wysuszone', 'Czas wyjąć pranie', 'Suszenie się skończyło'] | random }}
        target:
          entity_id: tts.google_cloud_2
    mode: single
