sensor:
  - platform: scrape
    name: Tauron_energy_cost
    resource: http://www.cena-pradu.pl/tabela.html
    select: ".WordSection1 > table:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > div > table > tr:nth-child(7) > td:nth-child(6) > p:nth-child(1) > b:nth-child(1) > span:nth-child(1)"
    index: 0
    unit_of_measurement: 'PLN/kWh'
    value_template: >
      {{ value.split("-")[0] | replace(",",".") | float(default=0) }}
    scan_interval: 3600

  - platform: scrape
    name: Tauron_static_cost
    resource: http://www.cena-pradu.pl/tabela.html
    select: ".WordSection1 > table:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > div > table > tr:nth-child(7) > td:nth-child(6) > p:nth-child(1) > b:nth-child(1) > span:nth-child(1)"
    index: 1
    unit_of_measurement: 'PLN'
    value_template: >
      {{ value.split("-")[0] | replace(",",".") | float(default=0) }}
    scan_interval: 3600

  - platform: pgnig_gas_sensor
    username: !secret pgnig_username
    password: !secret pgnig_password

  - platform: template
    sensors:
      grzejnik_voltage:
        value_template: >-
          {{ states.switch.grzejnik.attributes.voltage }}
        unit_of_measurement: 'V'
      grzejnik_current:
        value_template: >-
          {{ states.switch.grzejnik.attributes.current }}
        unit_of_measurement: 'mA'
      grzejnik_power:
        value_template: >-
          {{ states.switch.grzejnik.attributes.current_consumption }}
        unit_of_measurement: 'W'
        device_class: power

  - platform: integration
    source: sensor.grzejnik_power
    name: Grzejnik Energy
    unit_prefix: k
    round: 2