input_number:
  heating_time:
    name: "Czas działania grzejnika"
    unit_of_measurement: min
    min: 0
    max: 90
    step: 1
    initial: 30
    icon: mdi:timer

input_datetime:
  heating_start:
    name: "Godzina włączenia grzejnika"
    has_date: false
    has_time: true
    initial: "22:30:00"

automation:
  - id: '1615319114511'
    alias: Turn on bathroom heater at night
    description: 'Turn on bathroom heater at night'
    trigger:
    - platform: time
      at: input_datetime.heating_start
    condition: []
    action:
    - service: switch.turn_on
      target:
        entity_id: switch.grzejnik
    mode: single

  # - alias: Turn off bathroom heater after timer
  #   id: '1615319114512'
  #   trigger:
  #     - platform: event
  #       event_type: timer.finished
  #       event_data:
  #         entity_id: timer.heater
  #   action:
  #     - service: switch.turn_off
  #       target:
  #         entity_id: switch.grzejnik

  - id: '1615319114512'
    alias: Turn off bathroom heater after timer
    description: "Automatyczne wyłączanie grzejnika"
    trigger:
    - platform: state
      entity_id: switch.grzejnik
      to: 'on'
      for:
        minutes: "{{ states('input_number.heating_time')|int }}"
    action:
    - service: switch.turn_off
      entity_id: switch.grzejnik
