automation:
  - id: "1615319114500"
    alias: Turn on lampka u Hani after pressing button1
    description: ""
    trigger:
      - trigger: state
        entity_id: sensor.button1_action
        to: single
      - trigger: state
        entity_id: sensor.switch1_action
        to: single
    condition: []
    action:
      - action: light.toggle
        target:
          entity_id: light.lampka_u_hani
    mode: single
