scene:
  # TODO

script:
  home_arrive:
    alias: Home
    sequence:
      - choose:
        - conditions:
            - condition: state
              entity_id: light.fire_tablet_screen
              state: 'on'
            - condition: state
              entity_id: switch.fire_tablet_screensaver
              state: 'off'
          sequence:
            - service: tts.google_cloud_say
              data:
                entity_id: media_player.fire_tablet_media_player
                message: >
                  {{ ['Witaj', 'Cześć', 'Hej', 'Witaj w domu'] | random }}
      - choose:
        - conditions:
            - condition: state
              entity_id: sun.sun
              state: below_horizon
          sequence:
            - service: scene.turn_on
              data:
                entity_id: scene.dom_ponizej_horyzontu
        default:
          - service: scene.turn_on
            data:
              entity_id: scene.dom_powyzje_horyzontu
      - delay:
          seconds: 4

  home_leave:
    alias: Close everything
    sequence:
      - service: tts.google_cloud_say
        data:
          entity_id: media_player.nest_mini
          message: >
            {{ ['Do widzenia', 'Pa Pa', 'Cześć', 'Już za tobą tęsknię', 'Wyłączam wszystko'] | random }}
      - service: homeassistant.turn_off
        data:
          entity_id: >
            {% set states = [
              states.light.all_lights_exclude_hall,
              states.light.yeelight_hania,
              states.switch.wemo_fan,
              states.switch.wemo_monitors,
              states.switch.radio,
              states.switch.balkong,
              states.switch.tv,
              states.fan.sovrum_anslut ] %}
            {{ states | selectattr('state','eq','on') | map(attribute='entity_id') | list }}
      - delay:
          seconds: 1
      - service: fan.turn_off
        entity_id: fan.zhimi_airpurifier_v7
      - delay:
          seconds: 4