automation:
  - id: telegram-camera-ss
    alias: Camera command
    initial_state: true
    trigger:
      trigger: event
      event_type: telegram_command
      event_data:
        command: /camera
    action:
      - action: telegram_bot.send_message
        target:
          entity_id: notify.telegram_bot_5421860582_1469896663
        data:
          message: Kamery
      - action: script.camera_snapshot

  - id: telegram-start
    alias: Telegram Start Command
    initial_state: true
    trigger:
      trigger: event
      event_type: telegram_command
      event_data:
        command: /start
    action:
      - action: telegram_bot.send_message
        target:
          entity_id: notify.telegram_bot_5421860582_1469896663
        data:
          message: "{{ [ \"Hi, I'm your housekeeper .. I'll list you below \
            \ list of available commands \", \" How can I help you? \", \" Yes Sir! \"\
            , \"If you really insist, this is the command list \", \"Aaaaa .. more here? \",
            \" Nice to see you again\"] | random }}       \n"
          keyboard:
            - /nico, /mamma
            - /nicopcon, /nicopcoff, /nicopcreboot
            - /ping, /camera
            - /start, /cp

  - alias: Telegram_Bot_Stop
    id: telegram-stop
    trigger:
      - trigger: event
        event_type: telegram_callback
        event_data:
          data: /stop
    action:
      - action: telegram_bot.send_message
        target:
          entity_id: notify.telegram_bot_5421860582_1469896663
        data:
          message: "*Control Panel*"
          inline_keyboard:
            - 💡 Lights:/lights, 🚨 Security:/security
            - 💻 System:/system, 💻 Status:/status, Help:/help, Ping:/ping
            - 📄 Summary:/summary, ☀ Weather:/weather
            - Addons:/addons

  - id: telegram-control-pannel-start
    alias: Telegram Control Pannel Command
    initial_state: true
    trigger:
      trigger: event
      event_type: telegram_command
      event_data:
        command: /cp
    action:
      - action: telegram_bot.send_message
        target:
          entity_id: notify.telegram_bot_5421860582_1469896663
        data:
          message:
            "{{ [ \"Home Assistant Status\", \"Control Panel\", \"Yes Sir!\", \"\
            Home Assistant Control Panel\" ] | random }}  \
            \     \n"
          inline_keyboard:
            - 💡 Lights:/lights, 🚨 Security:/security
            - 💻 System:/system, ℹ Status:/status, Help:/help, Ping:/ping
            - 📄 Summary:/summar, ☀ Weather:/weather
            - Addons:/addons

  - id: telegram-ik-ping-pong
    alias: telegram ping pong
    trigger:
      - trigger: event
        event_type: telegram_callback
        event_data:
          data: /ping
    action:
      - action: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: "{{ trigger.event.data.id }}"
          message:
            'Callback received from {{ trigger.event.data.message.from.username }}. Message
            id: {{ trigger.event.data.message.message_id }}. Data: {{ trigger.event.data.data
            }} {{now().strftime("%Y-%m-%d %H:%M:%S")}} Pong, Message from {{ trigger.event.data.message.chat.username }}.'
          show_alert: true

script:
  camera_snapshot:
    alias: Camera Snapshot
    sequence:
      - action: telegram_bot.send_photo
        data:
          caption: "Main Camera Snapshot"
          target:
            - !secret telegram_anarion_chat_id
          url: !secret camera_main_still_image_url
      - action: telegram_bot.send_photo
        data:
          caption: "Garage Camera Snapshot"
          target:
            - !secret telegram_anarion_chat_id
          url: !secret camera_garage_still_image_url
      - action: telegram_bot.send_photo
        data:
          caption: "Garden Camera Snapshot"
          target:
            - !secret telegram_anarion_chat_id
          url: !secret camera_garden_still_image_url
# telegram_bot:
#   - platform: polling
#     api_key: !secret telegram_api_key
#     allowed_chat_ids:
#       - !secret telegram_anarion_chat_id
