homeassistant:
  customize:
    vacuum.valetudeo_dreame1:
      icon: cil:roborock-vacuum
    input_boolean.vacuum_livingroom:
      room_id: "1"
    input_boolean.vacuum_dining:
      room_id: "3"
    input_boolean.vacuum_kitchen:
      room_id: "4"


input_boolean:
  vacuum_livingroom:
    name: salon
    icon: mdi:sofa
    initial: true
  vacuum_dining:
    name: Jadalnia
    icon: mdi:silverware-fork-knife
    initial: true
  vacuum_kitchen:
    name: Kuchnia
    icon: mdi:countertop-outline
    initial: true

template:
  - sensor:
      - unique_id: vacuum_filter
        state: >
          {% set entity_id = 'sensor.valetudo_dreame1_main_filter' %}
          {{ (states(entity_id) | float(default=0) / 1440) | round(2) | float(default=0)}}
        attributes:
          friendly_name: Filtr
          icon: cil:roborock-filter
          unit_of_measurement: 'd'

      - unique_id: vacuum_mainbrush
        state: >
          {% set entity_id = 'sensor.valetudo_dreame1_main_brush' %}
          {{ (states(entity_id) | float(default=0) / 1440) | round(2) | float(default=0)}}
        attributes:
          friendly_name: Główna szczotka
          icon: cil:roborock-mainbrush
          unit_of_measurement: 'd'

      - unique_id: vacuum_sensors
        state: >
          {% set entity_id = 'sensor.valetudo_dreame1_sensor_cleaning' %}
          {{ (states(entity_id) | float(default=0) / 1440) | round(2) | float(default=0)}}
        attributes:
          friendly_name: Czystość czujnika
          icon: cil:roborock-sensor
          unit_of_measurement: 'd'

      - unique_id: vacuum_sidebrush
        state: >
          {% set entity_id = 'sensor.valetudo_dreame1_right_brush' %}
          {{ (states(entity_id) | float(default=0) / 1440) | round(2) | float(default=0)}}
        attributes:
          friendly_name: Boczna szczotka
          icon: cil:roborock-sidebrush
          unit_of_measurement: 'd'

group:
  vacuum_rooms:
    name: Vacuum Rooms
    entities:
      - input_boolean.vacuum_dining
      - input_boolean.vacuum_kitchen
      - input_boolean.vacuum_livingroom

script:
  vacuum_clean_segments:
    sequence:
    - service: script.turn_on
      target:
        entity_id: script.vacuum_clean_segments_message
      data:
        variables:
          segments: '{{expand("group.vacuum_rooms") | selectattr("state","eq","on")
            | map(attribute="attributes.room_id") | list | to_json}}'
    mode: single
    alias: vacuum_clean_segments
    icon: mdi:arrow-right
  vacuum_clean_segments_message:
    alias: vacuum_clean_segments_message
    sequence:
    - service: mqtt.publish
      data:
        topic: valetudo/dreame1/MapSegmentationCapability/clean/set
        payload_template: '{"segment_ids": {{ segments }}, "iterations": 1, "customOrder": false}'
    mode: single
