# rest:
#   - resource: http://192.168.2.241:5678
#     sensor:
#       name: youtube_watching
#       value_template: >
#         {% set video_id = value_json.video_id %}
#         https://img.youtube.com/vi/{{video_id}}/maxresdefault.jpg
#       json_attributes:
#         - channel
#         - title
#         - video_id
#         - duration_string
#         - thumbnail
#         - original_url
#     scan_interval: 86400

automation:
  - alias: update_youtube_watching_thumbnail
    id: '1781428593188'
    mode: single
    max_exceeded: silent
    variables:
      ytw: sensor.youtube_watching
    trigger:
      platform: state
      entity_id:
        - media_player.bravia_4k_gb_es_192_168_2_101
        - media_player.kd_55xe9305
        - media_player.nvidia_shield
        - media_player.shield
        - media_player.sony_kd_55xe9305
      to: playing
    condition: >
      {{ is_state_attr(trigger.entity_id, 'app_id', 'com.google.android.youtube') and
      state_attr(trigger.entity_id, 'media_title') != state_attr(ytw, 'title') }}
    action:
      - service: homeassistant.update_entity
        target:
          entity_id: '{{ ytw }}'