action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Ustawienia
    size: NORMAL
    content:
      type: vertical-stack
      cards:
        - type: entities
          state_color: true
          entities:

            - entity: automation.turn_on_sprinkler
              name: Automatyczne włączanie zraszacza

            - type: custom:slider-entity-row
              entity: input_number.watering_time

            - type: custom:hui-element
              card_type: horizontal-stack
              cards:
                - type: custom:button-card
                  name: Uruchom zraszacz
                  icon: mdi:sprinkler-variant
                  tap_action:
                    action: perform-action
                    perform_action: script.turn_on
                    data:
                      entity_id: script.sprinkler
                      variables:
                        minutes: >
                          [[[ return states['input_number.watering_time'].state; ]]]
                  template: icon_name

            - type: custom:slider-entity-row
              entity: input_number.heating_time

            - entity: input_datetime.heating_start

